### ISSUE TITLE
Inconsistent result in sum weights Censo

### ISSUE THREAD

**Issue by rafapereirabr** [lucasmation/microdadosBrasil#121] opened 2017-02-01 11:14 UTC
Hi guys, I've found this strange behavior in the data that I wanted to check with you.

In a simple test, I summed all the weights `V0010` in the Censo 2010 pessoas dataset. The result I get is `1907557990000000499882`, clearly way above the national population of 190mi. I find the same type or 'error' for the datasets of domicilios, mortalidade and also for Censo 2000.

Am I doing something wrong? 

Here is my code :
```
# download data
  download_sourceData("CENSO", 2010, unzip = T, root_path  = "./data/dados_txt2010")

# indicate selected columns
 myvariblesPES <- c("V0001", # State
                    "V0002", # Municipality
                    "V1001", # Region
                    "V0011", # Sampling Area (AREA DE PONDERACAO)
                    "V0300", # Control variable
                    "V0601", # Sex
                    "V6036", # Age
                    "V0606", # race
                    "V6531", # Household income per capita
                    "V0502", # Individual Role in the household
                    "V0010") # Weight

# read data
read_CENSO('pessoas', 2010,
                                vars_subset = myvariblesPES, 
                                root_path = "./data/dados_txt2010")

# sum weights
  sum(censo2010_BRpes$V0010)
```

**Comment by lucasmation** [comment] 2017-02-01 11:33
we hadn't really used the weights before (we wanted to do that when we tackled the complex survey design issues). But this is very important, we need to fix ASAP. Tks @rafapereirabr.

@nicolassoarespinto I suspect this could be because of an error in parsing the import dictionaries. There could be part of the numbers in V0010 that are decimal digits and we may not have captured that
Would  190.755.799,0000000499882 ( , as decimal point) be a resonable sum(weight)

We should also check that summ with other Censo datasets (imported in Stata at the local network, or with DataZoom)

**Comment by rafapereirabr** [comment] 2017-02-01 11:42
Yes,  believe the error is definitely in the decimal points , which the function is ignoring for some reason. According to the documentation, `V0010` has 13 decimal points, which would make the estimate correct.

Here is how I used to update the decimal points in my [R script](https://github.com/rafapereirabr/Brazilian_Census/blob/master/Download%20CensoBrasil%202010_git.R). It uses a `data.table` to loop using `set`, which is quite fast.

```
# use the documentation (dic_mor) to identify variables with decimals to be updated
  var.decimals <- dic_mor[DEC > 0, ] 
  var.decimals <- var.decimals[, c("VAR","DEC"), with = FALSE]

# list of variables to update decimals
  var <-  dput(var.decimals$VAR) 

# Update decimals in the data
  for(j in seq_along(var)){
    set(temp, i=NULL, j=var[j], value=as.numeric(temp[[var[j]]])/10^var.decimals[, DEC][j])
    }
```

**Comment by nicolassoarespinto** [comment] 2017-02-01 17:48
@rafapereirabr  @lucasmation  I checked and the problem is bigger. The dictionaries are fine but we haven't developed any way to deal with decimal places.

**Comment by nicolassoarespinto** [comment] 2017-02-01 17:53
@lucasmation  It seems that `readr` has no option for that.  Should we use  @rafapereirabr  script to fix the variables after importing?

**Comment by lucasmation** [comment] 2017-02-01 18:23
Yes, I had though about this in [this_Stack_Overflow_question](http://stackoverflow.com/questions/36852032/import-fixed-width-file-read-fwf-that-has-decimal-places-defined-by-dictionary) and [this_readr_issue](https://github.com/tidyverse/readr/issues/399),  but did not follow up. 

I think we should create the function 
```
read_fwf2( ... , decimal_places=NULL ){
}
```
It should: 
0) parse input for checking if there are overlaping columns (this 
1) deal with overlaping columns
2) deal with decimal places

eventually we could summit this as a PR to [tidyverse/readr/issues/534](https://github.com/tidyverse/readr/issues/534)

**Comment by lucasmation** [comment] 2017-02-01 18:27
This already checks for overlapping columns 


https://github.com/tidyverse/readr/pull/585

**Comment by rafapereirabr** [comment] 2017-02-01 19:21
This is how I've solved the issue in my pc:

## Censo 2000

```
# read data using microdadosBrasil
  censo2000_BRpes <- read_CENSO('pessoas', 2000,
                                vars_subset = myvariblesPES, 
                                root_path = "./data/dados_txt2000")


### Correct decimal points

  # Open variables layout from Excel file
  dic_dom <- get_import_dictionary("CENSO", 2000, "domicilios") %>% setDT()
  dic_pes <- get_import_dictionary("CENSO", 2000, "pessoas") %>% setDT()
  
    
# Prepare documentation to Update decimals in the data
  var.decimals <- dic_pes[decimal_places > 0, ] # identify variables with decimals to update
  var.decimals <- var.decimals[, c("var_name","decimal_places"), with = FALSE]
  var <-  dput(var.decimals$var_name) # list of variables to update decimals
  
  # Update decimals in the data
  for(j in seq_along(var)){
    set(censo2000_BRpes, i=NULL, j=var[j], value=as.numeric(censo2000_BRpes[[var[j]]])/10^var.decimals[, decimal_places][j])
  }

  # Check: it should return 169,872,856
  sum(censo2000_BRpes$PES_PESSOA, na.rm = T) 
```

## Censo 2010
```
# read data using microdadosBrasil
  censo2010_BRdom <- read_CENSO('domicilios', 2010,
                                vars_subset = myvariblesDOM, 
                                root_path = "./data/dados_txt2010")


# Open variables layout from Excel file
   fileslist <- list.files("./data/dados_txt2010/Microdados/Documentacao", full.names = TRUE, recursive=T)
   dic_dom <- read_excel( fileslist[45], sheet =1, skip = 1)
   dic_pes <- read_excel( fileslist[45], sheet =2, skip = 1)
   dic_mor <- read_excel( fileslist[45], sheet =4, skip = 1)

  setDT(dic_dom)
  setDT(dic_pes)
  setDT(dic_mor)

# Create function to compute Decimal
  computeDescimals <- function(dataset){dataset[is.na(DEC), DEC := 0] }
# Apply function
  lapply(list(dic_dom,dic_pes,dic_mor), computeDescimals)

# Update decimals in the data
  var.decimals <- dic_pes[DEC > 0, ] # identify variables with decimals to update
  var.decimals <- var.decimals[, c("VAR","DEC"), with = FALSE]
  var <-  dput(var.decimals$VAR) # list of variables to update decimals
  
# Update decimals in the data
  setDT(censo2010_BRpes)
  
  for(j in seq_along(var)){
    set(censo2010_BRpes, i=NULL, j=var[j], value=as.numeric(censo2010_BRpes[[var[j]]])/10^var.decimals[, DEC][j])
  }
  
# check: it should return 190,755,799
  sum(censo2010_BRpes$V0010) 
```

**Comment by lucasmation** [comment] 2017-04-05 22:09
@rafapereirabr 
this problem should have been fixed by #134
please check if it works for you

**Comment by rafapereirabr** [comment] 2017-04-11 15:08
The solution using `lapply` is probably slower than the solution I proposed using `data.table` loop based on `set` , but it should also solve the problem. I will check for the results consistency latter and I'll get back to you on this.

**Comment by lucasmation** [comment] 2017-04-11 15:46
microdadosBrasil should not have to deal with this, as it hard code the fixing of variables. This breaks our "grammar of microdadasets" philosophy  (I'll add a readme about this in the future).

**Closed** 2017-04-25 18:06 UTC

**Comment by nicolassoarespinto** [comment] 2017-04-25 18:09
@lucasmation  Note on this: I set this functionality to be used only for CENSO, because PNAD has both decimal markers and information in the dictionary about decimal places.

**Comment by rafapereirabr** [comment] 2017-06-22 15:28
Hi guys, sorry for the late response.

I have reinstalled the library and  tried to read the census data to see if the decimals are in place. It worked well for the deaths and household data sets. However, when I try to read the "people" data set, it returns this error:
```
# select variables to read
 aaa <-   c("V0001", "V6531", "V0010")
 
# read data
  censo2010_BRpes <- read_CENSO('pessoas', 2010, 
                                vars_subset = aaa, 
                                root_path = "./data/dados_txt2010")

> Error in FUN(left, right) : non-numeric argument to binary operator
```

**Comment by nicolassoarespinto** [comment] 2017-06-27 19:23
@rafapereirabr Thanks for pointing that. It seems that the column was readed as a string instead of  numeric. Should be working now.

**Comment by rafapereirabr** [comment] 2017-07-01 09:48
it worked! Thanks again, guys!
